name: social-agents
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - matplotlib
  - numpy=1.26.4
  - pyyaml
  - imageio
  - matplotlib
  - pandas
  - seaborn
  - pytorch
  - pip
  - pip:
    - chex
    - ipython
    - -e ./tonic  # editable install of tonic
    - -e .  # editable install of this package (social_agents)
